# Generated by Django 5.2.8 on 2025-11-21 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_event_image_alter_album_type_smtpsetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-date_added',), 'verbose_name': 'News', 'verbose_name_plural': 'News Articles'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='news',
            name='published_date',
        ),
    ]
