# Generated by Django 5.2.8 on 2025-11-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_news_options_remove_news_publish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='mobile',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
