# Generated by Django 5.2.8 on 2025-11-21 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_enquiry_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='organizer',
            new_name='organiser',
        ),
    ]
